### ISSUE TITLE
Project Incompatible with Current Edition

### ISSUE THREAD

**Issue by jordanbaucke** [QuantConnect/QCStudioPlugin#7]
Trying to work with this as I'd like to work in VS versus the web-IDE

When I load the solution in Visual Studio 2013 Ultimate Edition, I get `This project is incompatible with current edition` for each of the project files.

Any suggestions?

**Comment by jaredbroad** [comment]
Hey Jordan, officially the plugin is deprecated and we're planning on rewriting it soon. There were several threading issues which cause lock up, and the charting does not support custom charts. We're going to rewrite to use LEAN and HTML5 charting.

The project is left here for posterity as several users request it.
